### ISSUE TITLE
split CDX files by "log"-date

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#47]
See https://github.com/sul-dlss/web-archiving/wiki/Indexing#agreed-c-proposal-to-split-cdx-files-by-log-date

There will be 4 CDX index files:

- Layer 0 - today's index
- Layer 1 - this month's index
- Layer 2 - this year's index
- Layer 3 - the rest of the index

Both was_robot_suite and openwayback need changes as follows:

- [x] Verify that a simple rename of the current index into the Layer 3 index works in the new configuration (PR https://github.com/sul-dlss/openwayback/pull/26)
- [x] Change configuration of openwayback to use multiple CDX index files (see https://github.com/sul-dlss/openwayback/issues/25)
- [x] Change wasCrawlDissemination robots to only operate on Level 0 index file (PR #48)
- [x] Implement cronjob that rolls up the index files into Level 0, 1, 2, and 3 (PR #48)
- [x] Implement locking mechanism so that cronjob doesn't run when robots are doing work on the Level 0 index file, or other cronjobs are doing work on other levels. (PR #48)

**Comment by drh-stanford** [comment]
For the cronjob, we basically follow this logic -- assumes a level3 data file:

- Daily, merge all level0 data into level1, and leave an empty level0 file
- Monthly, merge all level1 data into level2, and leave an empty level1 file
- Yearly, merge all level2 data into level3, and leave an empty level2 file

**Comment by drh-stanford** [comment]
I have all the PRs listed above in the checklist. We need to test out this solution in stage/dev first which requires deploying branches to openwayback VMs and was-robots1 VMs.

**Comment by drh-stanford** [comment]
When PR #48 is merged, the procedure for the _first_ deployment will be:

```
% ssh was-robots1-xxx
% cd was_robot_suite/current
% ROBOT_ENVIRONMENT=xxx bundle exec rake cdx:index:admin:migrate
```

**Comment by drh-stanford** [comment]
This is deployed in stage now and ready for testing pushing some crawl objects through...

**Comment by drh-stanford** [comment]
also PR https://github.com/sul-dlss/puppet/pull/1484

**Comment by drh-stanford** [comment]
in production now
