### ISSUE TITLE
specs with image_prerequisite should NOT be skipped

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#497]
As part of PR #494, I discovered that some of the specs have a tag `image_prerequisite` .. and those specs are NOT being run.  So we haven't been running tests on the thumbnail image generation for a loooooooong time.

I know this because one such spec uses VCR ... and that gem isn't in the Gemfile, nor does the VCR cassette exist in the repo at this time.  Here are the specs in question.

- [x] `capture_thumbnail` https://github.com/sul-dlss/was_robot_suite/blob/main/spec/lib/dor/was_seed/thumbnail_generator_service_spec.rb#L23 -- addressed in PR #494
- [x]  `.screenshot` https://github.com/sul-dlss/was_robot_suite/blob/main/spec/lib/dor/was_seed/thumbnail_generator_service_spec.rb#L48 -- we need a warc, I think, that we can use in mocks (?)  @edsu??  (there is one in integration tests) -- this should be testing that we get a screenshot of the warc - created issue #510 for this;  refactored specs in PR #505 to call out the lack of testing for this.
- [x]  `.resize_jpeg` ~~https://github.com/sul-dlss/was_robot_suite/blob/main/spec/lib/dor/was_seed/thumbnail_generator_service_spec.rb#L49 -- Naomi is working on these already with Tony C.  (includes spec/lib/dor/was_seed/thumbnail_generator_service_spec.rb#L72)~~ --  addressed by PR #504
- [ ]  https://github.com/sul-dlss/was_robot_suite/blob/main/spec/lib/dor/was_seed/content_metadata_generator_service_spec.rb#L67
- [ ]  https://github.com/sul-dlss/was_robot_suite/blob/main/.rspec - remove line skipping image_prerequisite tagged specs
